/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.Estacion;
import static Interfaces.CargarRed.grafoApp;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author salom
 */
public class AgregarLinea extends javax.swing.JFrame {
    private DefaultComboBoxModel modeloadyacencia1;
    private DefaultComboBoxModel modeloadyacencia2;
    private ComboBoxModel<String> primeraAdyacencia; //las agregué pq me daba error y netbeans lo sigirió
    private ComboBoxModel<String> modeloAdyacencia2; //las agregué pq me daba error y netbeans lo sigirió
    
    /**
     * Creates new form AgregarLinea
     */
    public AgregarLinea() {
        modeloadyacencia1 = new DefaultComboBoxModel();
        modeloadyacencia2 = new DefaultComboBoxModel();
        initComponents();
        this.setResizable(false);
    }
    
    private void modificarComboBoxes(){
        this.cargarAdyacenciasBox1();
        this.cargarAdyacenciasBox2();
        
    }
    
    private void cargarAdyacenciasBox1(){
        modeloadyacencia1.removeAllElements();
        if(grafoApp.verEstaciones()!= null){
            for(int i = 0; i< grafoApp.verEstaciones().getSize(); i++){
                String nombreEstacion =(String) grafoApp.verEstaciones().getValor(i);
                modeloadyacencia1.addElement(nombreEstacion);
            }
        }
    }
    
    private void cargarAdyacenciasBox2(){
        modeloadyacencia2.removeAllElements();
        if(grafoApp.verEstaciones()!= null){
            for(int i = 0; i< grafoApp.verEstaciones().getSize(); i++){
                String nombreEstacion =(String) grafoApp.verEstaciones().getValor(i);
                modeloadyacencia2.addElement(nombreEstacion);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nuevaEstacion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        agregarEstacion = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Menu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        agregarAdyacencia = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        modelAdyacencia1 = new javax.swing.JComboBox<>();
        modelAdyacencia2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Escriba el nombre de la estación.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 270, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AGREGAR LINEA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 350, 40));

        nuevaEstacion.setBackground(new java.awt.Color(255, 255, 255));
        nuevaEstacion.setForeground(new java.awt.Color(0, 0, 0));
        nuevaEstacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaEstacionActionPerformed(evt);
            }
        });
        getContentPane().add(nuevaEstacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 270, 30));

        jPanel2.setBackground(new java.awt.Color(102, 0, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 204), new java.awt.Color(153, 0, 204), new java.awt.Color(51, 0, 102), new java.awt.Color(51, 0, 102)));
        jPanel2.setForeground(new java.awt.Color(102, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarEstacion.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        agregarEstacion.setForeground(new java.awt.Color(255, 255, 255));
        agregarEstacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarEstacion.setText("AGREGAR");
        agregarEstacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarEstacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarEstacionMouseClicked(evt);
            }
        });
        jPanel2.add(agregarEstacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 130, 30));

        jPanel4.setBackground(new java.awt.Color(102, 0, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 255), new java.awt.Color(204, 0, 255), new java.awt.Color(51, 0, 102), new java.awt.Color(51, 0, 102)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        Menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu.setText("MENU");
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
        });
        jPanel4.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 240, 50));

        jPanel3.setBackground(new java.awt.Color(102, 0, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 255), new java.awt.Color(204, 0, 255), new java.awt.Color(51, 0, 102), new java.awt.Color(51, 0, 102)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarAdyacencia.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        agregarAdyacencia.setForeground(new java.awt.Color(255, 255, 255));
        agregarAdyacencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarAdyacencia.setText("AGREGAR");
        agregarAdyacencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarAdyacencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarAdyacenciaMouseClicked(evt);
            }
        });
        jPanel3.add(agregarAdyacencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 130, 50));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Seleccione las adyacencias.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 270, -1));

        modelAdyacencia1.setBackground(new java.awt.Color(255, 255, 255));
        modelAdyacencia1.setForeground(new java.awt.Color(0, 0, 0));
        modelAdyacencia1.setModel(primeraAdyacencia);
        getContentPane().add(modelAdyacencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 270, 30));

        modelAdyacencia2.setBackground(new java.awt.Color(255, 255, 255));
        modelAdyacencia2.setForeground(new java.awt.Color(0, 0, 0));
        modelAdyacencia2.setModel(modeloAdyacencia2);
        getContentPane().add(modelAdyacencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 270, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaEstacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaEstacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevaEstacionActionPerformed

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        Menu v2 = new Menu();
        v2.setLocationRelativeTo(null);
        v2.setResizable(false);
        v2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuMouseClicked

    private void agregarEstacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarEstacionMouseClicked
       if(!"".equals(nuevaEstacion.getText())){
           String nombre = nuevaEstacion.getText();
           Estacion nombreEstacion = new Estacion(nombre);
           grafoApp.agregarEstacion(nombreEstacion);
           this.modificarComboBoxes();
        }else{
             JOptionPane.showMessageDialog(null, "Por favor escribir el nombre de una estacion");
        }
    }//GEN-LAST:event_agregarEstacionMouseClicked

    private void agregarAdyacenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarAdyacenciaMouseClicked
        if(!modelAdyacencia1.getSelectedItem().equals(modelAdyacencia2.getSelectedItem())){
            String nombreEstacion1 = (String) modelAdyacencia1.getSelectedItem();
            String nombreEstacion2 = (String) modelAdyacencia2.getSelectedItem();
            
            grafoApp.agregarConexion(nombreEstacion1, nombreEstacion2);
            this.modificarComboBoxes();
        }else{
            JOptionPane.showMessageDialog(null, "No se puede realizar una conexion haci si mismo. La ciudad Inicio y Final deben ser diferentes.");
        }
    }//GEN-LAST:event_agregarAdyacenciaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarLinea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel agregarAdyacencia;
    private javax.swing.JLabel agregarEstacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> modelAdyacencia1;
    private javax.swing.JComboBox<String> modelAdyacencia2;
    private javax.swing.JTextField nuevaEstacion;
    // End of variables declaration//GEN-END:variables
   
}
