/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author salom
 */
public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        agregarLinea = new javax.swing.JLabel();
        colocarSucursal = new javax.swing.JLabel();
        verCobertura = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        cargarRed = new javax.swing.JLabel();
        mostrarGrafo = new javax.swing.JLabel();
        establecerT = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        agregarLinea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarLinea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarLineaMouseClicked(evt);
            }
        });
        getContentPane().add(agregarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 310, 60));

        colocarSucursal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        colocarSucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colocarSucursalMouseClicked(evt);
            }
        });
        getContentPane().add(colocarSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 310, 60));

        verCobertura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verCobertura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verCoberturaMouseClicked(evt);
            }
        });
        getContentPane().add(verCobertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 310, 60));

        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 320, 70));

        cargarRed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cargarRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarRedMouseClicked(evt);
            }
        });
        getContentPane().add(cargarRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 300, 60));

        mostrarGrafo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarGrafo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarGrafoMouseClicked(evt);
            }
        });
        getContentPane().add(mostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 310, 60));

        establecerT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        establecerT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                establecerTMouseClicked(evt);
            }
        });
        getContentPane().add(establecerT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 300, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colocarSucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colocarSucursalMouseClicked
        ColocarSucursal cs = new ColocarSucursal();
        cs.setLocationRelativeTo(null);
        cs.setResizable(false);
        this.dispose();
        cs.setVisible(true);
    }//GEN-LAST:event_colocarSucursalMouseClicked

    private void agregarLineaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarLineaMouseClicked
        AgregarLinea al = new AgregarLinea();
        al.setLocationRelativeTo(null);
        al.setResizable(false);
        this.dispose();
        al.setVisible(true);
    }//GEN-LAST:event_agregarLineaMouseClicked

    private void verCoberturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verCoberturaMouseClicked
        VerCobertura v3 = new VerCobertura();
        v3.setLocationRelativeTo(null);
        v3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_verCoberturaMouseClicked

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        this.dispose();
        JOptionPane.showMessageDialog(null, "Gracias, hasta pronto!");
    }//GEN-LAST:event_salirMouseClicked

    private void cargarRedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarRedMouseClicked
        CargarRed cr = new CargarRed();
        cr.setLocationRelativeTo(null);
        this.dispose();
        cr.setVisible(true);
        cr.setResizable(false);
    }//GEN-LAST:event_cargarRedMouseClicked

    private void mostrarGrafoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarGrafoMouseClicked
        MostrarGrafo mg = new MostrarGrafo();
        mg.setLocationRelativeTo(null);
        mg.setResizable(false);
        this.dispose();
        mg.setVisible(true);
        
    }//GEN-LAST:event_mostrarGrafoMouseClicked

    private void establecerTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_establecerTMouseClicked
        EstablecerT et = new EstablecerT();
        et.setLocationRelativeTo(null);
        et.setResizable(false);
        this.dispose();
        et.setVisible(true);
    }//GEN-LAST:event_establecerTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregarLinea;
    private javax.swing.JLabel cargarRed;
    private javax.swing.JLabel colocarSucursal;
    private javax.swing.JLabel establecerT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mostrarGrafo;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel verCobertura;
    // End of variables declaration//GEN-END:variables
}
